[package]
name = "steamworks-sys"
version = "0.3.0"
authors = ["Thinkofname"]
build = "build.rs"
description = "Provides raw bindings to the steamworks sdk"
license = "MIT / Apache-2.0"
repository = "https://github.com/Thinkofname/steamworks-rs"
documentation = "https://docs.rs/steamworks-sys"

[package.metadata.docs.rs]
features = [ "docs-only" ]


[features]
default = []
# Skip looking for the steamworks sdk for docs builds
docs-only = []


[dependencies]
libc = "0.2.36"

[build-dependencies]
cc = "1.0.4"
bindgen = "0.36.0"
serde = "1.0.37"
serde_derive = "1.0.37"
serde_json = "1.0.14"

