[package]
name = "steamworks-sys"
version = "0.1.0"
authors = ["matt"]
build = "build.rs"
description = "Provides raw friendly bindings to the steamworks sdk"
license = "MIT / Apache-2.0"
repository = "https://github.com/Thinkofname/steamworks-rs"
documentation = "https://docs.rs/steamworks-sys"


[features]
default = []
# Skip looking for the steamworks sdk for docs builds
docs-only = []


[dependencies]
libc = "0.2.36"

[build-dependencies]
cc = "1.0.4"
