[package]
name = "steamworks"
version = "0.2.0"
authors = ["matt"]
description = "Provides rust friendly bindings to the steamworks sdk"
license = "MIT / Apache-2.0"
repository = "https://github.com/Thinkofname/steamworks-rs"
documentation = "https://docs.rs/steamworks"
keywords = ["steam", "gamedev"]
categories = ["games"]

[features]
default = []
# Skip looking for the steamworks sdk for docs builds
docs-only = ["steamworks-sys/docs-only"]

[workspace]
members = [
    "./steamworks-sys"
]

[dependencies]
steamworks-sys = {path = "./steamworks-sys", version = "0.1.0"}
failure = "0.1.1"
bitflags = "1.0.1"
libc = "0.2.36"

[package.metadata.docs.rs]
features = [ "docs-only" ]