[package]
name = "steamworks"
version = "0.1.0"
authors = ["matt"]

[workspace]
members = [
    "./steamworks-sys"
]

[dependencies]
steamworks-sys = {path = "./steamworks-sys", version = "0.1.0"}
failure = "0.1.1"
bitflags = "1.0.1"
libc = "0.2.36"
